export const KYC_TOKENS = {
  FILE_STORAGE: "KYC_FILE_STORAGE",
  DOCUMENT_EXTRACTION_PROVIDER: "KYC_DOCUMENT_EXTRACTION_PROVIDER",
  FACE_VERIFICATION_PROVIDER: "KYC_FACE_VERIFICATION_PROVIDER",
  FACE_AI_VERIFICATION_PROVIDER: "KYC_FACE_AI_VERIFICATION_PROVIDER",
} as const;
